apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: angelsfairy-poi-map-app-dev
  annotations:
    argocd/app-name: angelsfairy-poi-map-app-dev
    backstage.io/kubernetes-id: angelsfairy-poi-map-app
    backstage.io/kubernetes-namespace: angelsfairy
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/angelsfairy-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/angelsfairy/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/angelsfairy/deployments/angelsfairy-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/angelsfairy-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://angelsfairy-poi-map-app-angelsfairy.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/angelsfairy"
  system: workshop-system-angelsfairy
  consumesApis:
    - gateway-api-angelsfairy
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-angelsfairy
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/angelsfairy"
